// WebSourcesBar.jsx — AI-generated reference links shown at top of messages
import { useState } from 'react';
import { ExternalLink, TriangleAlert, X, BookOpen } from 'lucide-react';

const getDomain = (url) => {
  try { return new URL(url).hostname.replace('www.', ''); }
  catch { return url; }
};

// Styled confirmation modal
const LinkConfirmModal = ({ link, onConfirm, onCancel }) => (
  <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4">
    <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onCancel} />
    <div className="relative w-full max-w-sm bg-white dark:bg-gray-900 midnight:bg-slate-900 rounded-2xl shadow-2xl border border-gray-200 dark:border-gray-700 midnight:border-slate-700 overflow-hidden">
      <div className="flex items-center justify-between px-5 pt-5 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-full bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center flex-shrink-0">
            <TriangleAlert className="w-4 h-4 text-amber-600 dark:text-amber-400" />
          </div>
          <span className="font-semibold text-gray-900 dark:text-white text-sm">External link</span>
        </div>
        <button
          onClick={onCancel}
          className="w-7 h-7 flex items-center justify-center rounded-full text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
        >
          <X className="w-4 h-4" />
        </button>
      </div>
      <div className="mx-5 mb-4 px-3 py-2.5 bg-gray-50 dark:bg-gray-800 midnight:bg-slate-800 rounded-xl border border-gray-200 dark:border-gray-700">
        <div className="flex items-center gap-2 min-w-0">
          <img
            src={`https://icons.duckduckgo.com/ip3/${getDomain(link.url)}.ico`}
            alt=""
            className="w-4 h-4 rounded flex-shrink-0 object-contain"
            onError={(e) => { e.target.style.display = 'none'; }}
          />
          <span className="text-xs text-gray-500 dark:text-gray-400 truncate font-mono select-all">
            {link.url}
          </span>
        </div>
      </div>
      <p className="px-5 pb-4 text-xs text-gray-500 dark:text-gray-400 leading-relaxed">
        This link was generated by AI and <span className="font-medium text-gray-700 dark:text-gray-300">may not be accurate</span>. Verify the URL before proceeding.
      </p>
      <div className="flex gap-2 px-5 pb-5">
        <button
          onClick={onCancel}
          className="flex-1 px-4 py-2.5 rounded-xl text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
        >
          Cancel
        </button>
        <button
          onClick={onConfirm}
          className="flex-1 px-4 py-2.5 rounded-xl text-sm font-medium text-white bg-blue-500 hover:bg-blue-600 dark:bg-blue-600 dark:hover:bg-blue-500 transition-colors flex items-center justify-center gap-1.5"
        >
          Open <ExternalLink className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  </div>
);

const LinkChip = ({ link, index }) => {
  const [confirming, setConfirming] = useState(false);
  const domain = getDomain(link.url);

  const handleConfirm = () => {
    window.open(link.url, '_blank', 'noopener,noreferrer');
    setConfirming(false);
  };

  return (
    <>
      <button
        onClick={() => setConfirming(true)}
        title={link.url}
        className="group relative flex items-center gap-2.5 flex-shrink-0 pl-2 pr-3 py-2 bg-white dark:bg-gray-900 midnight:bg-slate-900 border border-gray-200 dark:border-gray-700/80 midnight:border-slate-700 rounded-xl hover:border-blue-400/60 dark:hover:border-blue-500/50 hover:shadow-sm hover:shadow-blue-500/5 transition-all text-left max-w-[190px]"
      >
        {/* Number badge */}
        <span className="flex-shrink-0 w-5 h-5 rounded-md bg-gray-100 dark:bg-gray-800 midnight:bg-slate-800 flex items-center justify-center text-[10px] font-semibold text-gray-400 dark:text-gray-500 group-hover:bg-blue-50 dark:group-hover:bg-blue-900/20 group-hover:text-blue-500 transition-colors">
          {index + 1}
        </span>
        <img
          src={`https://icons.duckduckgo.com/ip3/${domain}.ico`}
          alt=""
          className="w-3.5 h-3.5 rounded flex-shrink-0 object-contain"
          onError={(e) => { e.target.style.display = 'none'; }}
        />
        <div className="flex-1 min-w-0">
          <div className="text-[10px] text-gray-400 dark:text-gray-500 truncate leading-none mb-0.5">
            {domain}
          </div>
          <div className="text-xs text-gray-700 dark:text-gray-200 midnight:text-slate-200 truncate font-medium leading-snug">
            {link.title}
          </div>
        </div>
        <ExternalLink className="w-3 h-3 text-gray-300 dark:text-gray-600 group-hover:text-blue-400 transition-colors flex-shrink-0 ml-0.5" />
      </button>

      {confirming && (
        <LinkConfirmModal link={link} onConfirm={handleConfirm} onCancel={() => setConfirming(false)} />
      )}
    </>
  );
};

const WebSourcesBar = ({ links = [] }) => {
  if (!links || links.length === 0) return null;

  return (
    <div className="mb-5 pb-4 border-b border-gray-100 dark:border-gray-800 midnight:border-slate-800">
      {/* Header */}
      <div className="flex items-center gap-1.5 mb-2.5">
        <BookOpen className="w-3 h-3 text-gray-400 dark:text-gray-500" />
        <span className="text-[11px] font-semibold text-gray-400 dark:text-gray-500 midnight:text-slate-500 uppercase tracking-wider">
          Sources
        </span>
        <span className="text-[10px] text-gray-300 dark:text-gray-600 midnight:text-slate-700 ml-0.5">
          · AI-generated
        </span>
      </div>

      {/* Chips row */}
      <div className="flex items-center gap-2 overflow-x-auto pb-0.5 scrollbar-thin">
        {links.map((link, i) => (
          <LinkChip key={i} link={link} index={i} />
        ))}
      </div>

      {/* Disclaimer */}
      <p className="flex items-center gap-1 text-[10px] text-gray-300 dark:text-gray-600 midnight:text-slate-700 mt-2">
        <TriangleAlert className="w-2.5 h-2.5 flex-shrink-0" />
        Links may be incorrect — always verify before use
      </p>
    </div>
  );
};

// Parse <weblinks>[...]</weblinks> from message content
// Returns { links, cleanContent }
// eslint-disable-next-line react-refresh/only-export-components
export function parseWebLinks(content) {
  if (!content) return { links: [], cleanContent: content };
  const match = content.match(/<weblinks>([\s\S]*?)<\/weblinks>/);
  if (!match) return { links: [], cleanContent: content };

  let links = [];
  try {
    links = JSON.parse(match[1].trim());
    if (!Array.isArray(links)) links = [];
    links = links.filter(l => l && typeof l.title === 'string' && typeof l.url === 'string' && l.url.startsWith('http'));
  } catch {
    links = [];
  }

  const cleanContent = content.replace(/<weblinks>[\s\S]*?<\/weblinks>/, '').trimEnd();
  return { links, cleanContent };
}

export default WebSourcesBar;
